name: hugo publish

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true
        with: submodules:true

    - name: Build
      run: hugo --minify

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        PERSONAL_TOKEN: ${{ secrets.TOKEN }}
        PUBLISH_BRANCH: public
        PUBLISH_DIR: ./public
      with:
        emptyCommits: false
        keep_files: true
        commitMessage: ${{ github.event.head_commit.message }}
